### ISSUE TITLE
require context code regex match fail

### ISSUE THREAD

**Issue by XinChou16** [originjs/vite-plugins#13]
### Versions

- originjs: 1.0.7
- node: 14

### Reproduction

<details open>
<summary>Additional Details</summary>
<br>

```js
const components = getFilesByContext(require.context('../components/views', false, /\.vue$/));

```
</details>

### Steps to reproduce
1. pass the require.context return to a function params
2. the regex  matched fail

### What is Expected?
regex match right, no error

### What is actually happening?
error with Unexpected token ')'

**Comment by XinChou16** [comment]
This workes well 
```js

const matchedFiles = require.context('../components/views', false, /\.vue$/);
const components = getFilesByContext(matchedFiles);
```

**Comment by PeterAlfredLee** [comment]
Hi @XinChou16 
Thank you for your reporting. Will fix this soon.

**Comment by PeterAlfredLee** [comment]
Hi @XinChou16 
I have pushed a new version `1.0.8`. Please have a try.

**Comment by XinChou16** [comment]
> Hi @XinChou16 I have pushed a new version `1.0.8`. Please have a try.

The version v1.0.8 file seems as the same as v1.0.7

Here is the link
https://cdn.jsdelivr.net/npm/@originjs/vite-plugin-require-context@1.0.8/lib/index.js

**Comment by PeterAlfredLee** [comment]
Oops. I forgot to made a build before publish.

**Comment by PeterAlfredLee** [comment]
Hi @XinChou16 Please have a look at 1.0.9.

**Comment by XinChou16** [comment]
It works well with v1.0.9. Thanks a lot~
