### ISSUE TITLE
报错了，没有转换正确

### ISSUE THREAD

**Issue by vxhly** [originjs/vite-plugins#3]
![image](https://user-images.githubusercontent.com/17906558/124563749-e84e0f80-de72-11eb-81ad-143643b97a1f.png)
我想导入 config 文件夹下的相关文件，但是使用了该查价转换，转换失败

![image](https://user-images.githubusercontent.com/17906558/124564029-35ca7c80-de73-11eb-9e78-bc665b4809d6.png)

**Comment by vxhly** [comment]
我的 vite.config.js 是这么写的

``` javascript
import { defineConfig } from 'vite'
import legacyPlugin from '@vitejs/plugin-legacy' // 现代浏览器兼容
import { createVuePlugin } from 'vite-plugin-vue2' // 转换 vue 2.x 的语法
import ViteRequireContext from '@originjs/vite-plugin-require-context' // 转换 require.context 这种写法
import * as path from 'path'

const alias =
[
  { find: '@', replacement: path.resolve(__dirname, './src') },  { find: /^~/, replacement: '' }
]

export default defineConfig({
  base: './', // index.html文件所在位置
  root: './', // js导入的资源路径，src
  resolve: {
    alias
  },
  esbuild: {
    jsxFactory: 'h',
    jsxFragment: 'Fragment'
  },
  plugins: [
    ViteRequireContext({
      projectBasePath: process.cwd(),
      defaultRegExp: /^.*$/
    }),
    createVuePlugin({ jsx: true }),
    legacyPlugin({
      targets: ['Android > 39', 'Chrome >= 60', 'Safari >= 10.1', 'iOS >= 10.3', 'Firefox >= 54', 'Edge >= 15'],
      additionalLegacyPolyfills: ['regenerator-runtime/runtime']
    })
  ],
  build: {
    target: 'es2015',
    minify: 'terser',
    manifest: false,
    sourcemap: false,
    outDir: 'build',
    rollupOptions: {}
  },
  css: {
    preprocessorOptions: {
      less: {
        // 支持内联 JavaScript
        javascriptEnabled: true
      }
    }
  }
})

```

**Comment by PeterAlfredLee** [comment]
Hi @vxhly 
I just pushed a new version(1.0.4). Could you have a try again?

BTW : It's appreciated if you can provide some code to reproduce this problem(not the `vite.config.js`)
----------------
嗨@vxhly
我刚刚推送了一个新版本（1.0.4）。 你能再试一次吗？

顺便说一句：如果你能提供一些代码来重现这个问题（不是`vite.config.js`），我们将不胜感激

**Comment by vxhly** [comment]
这是 bug 错误的重现地址 https://gitee.com/vxhly/vite-plugin-bug-demo

**Comment by PeterAlfredLee** [comment]
Thanks @vxhly 

I have located the bug. But it seems there is a problem in `default.config.js` - the imported logo is invalid:
```
import logo from ''
```
I removed this from `default.config.js` and can successfully lauch the app with vite. I will push another fix soon.
<---------
谢谢@vxhly

我已经找到了错误。但是似乎`default.config.js` 中存在一个问题——导入的logo无效：
``
import logo from ''
``
我从 `default.config.js` 中删除了它，并且可以使用 vite 成功启动应用程序。我会尽快推动另一个修复。

**Comment by PeterAlfredLee** [comment]
I have pushed a new version `1.0.5`. I tested it with the gitee project and it can be successfully lauched.
Could you have a try again @vxhly ?
<-----
我已经推送了一个新版本“1.0.5”。我用gitee项目测试过，可以成功启动。
你能再试一次吗@vxhly？

**Comment by vxhly** [comment]
已经解决了

**Comment by PeterAlfredLee** [comment]
> 这一个新的功能请求，希望能转换以下的写法

IMO this is a bit difficult to implement. We are using regex matching and replacing to implement the `require.context` now, but I'm afraid your feature request needs AST or something else. I think we can not offer this by now.

And PRs are always welcome. :-)
<------
> 这一个新的功能请求，希望能转换以下的写法

IMO 这有点难以实施。我们现在正在使用正则表达式匹配和替换来实现 `require.context`，但恐怕您的功能请求需要 AST 或其他东西。我想我们现在不能提供这个。

PR 总是受欢迎的。 :-)

**Comment by PeterAlfredLee** [comment]
I'm closing this issue cause the problem is resolved.
Feel free to reopen this if needed.
