### ISSUE TITLE
key2FilesMap为空，导致报错  start of generated code of __require_context_for_vite_function_0

### ISSUE THREAD

**Issue by itlangzi** [originjs/vite-plugins#4]
![image](https://user-images.githubusercontent.com/26922527/126874254-d7d06f74-4db2-4e3a-83c3-b93efc813dbb.png)
【图1】
![image](https://user-images.githubusercontent.com/26922527/126874313-f821a9e9-943c-4665-a40f-27eec90d0e22.png)
【图2】
如【图1】，如果key2FilesMap为空 `{}` ，会导致【图2】的错误

**Comment by PeterAlfredLee** [comment]
Hi @itlangzi 
Thank you for your reporting.
Seems you are using `require.context` to search files and got nothing, and you are meant to do it like this. You are just expecting no error reporting, is it?
<----------------------------
Hi @itlangzi
感谢您的报告。
似乎您正在使用 `require.context` 来搜索文件而什么也没得到，而这正是您打算做的。你只是期望没有错误报告，是吗？

**Comment by PeterAlfredLee** [comment]
BTW: A PR is welcome.
顺便说一句：欢迎 PR。

**Comment by itlangzi** [comment]
@PeterAlfredLee 这个错误会导致vite编译不通过，debug发现是由于转换的代码少了一个`{`, 如issue中的【图2】，转换后正确的应该是 
```js
var _require_context_for_vite_map_0= {

}
```
原因是由于下面这句代码中有个`length-2`, 导致key2FilesMap为空的时候，转换的代码出现错误
```js
key2FilesMapString = key2FilesMapString.substring(0, key2FilesMapString.length - 2) + '\n};\n';
```

**Comment by PeterAlfredLee** [comment]
Could you provide some detailed code to reproduce this problem? thanks
你能提供一些详细的代码来重现这个问题吗？ 谢谢

**Comment by PeterAlfredLee** [comment]
Hi
