### ISSUE TITLE
vite-plugin-commonjs : not working for vite build

### ISSUE THREAD

**Issue by haiting** [originjs/vite-plugins#41]
vite-plugin-commonjs is not working for vite build 

### Versions

- @originjs/vite-plugin-commonjs: 1.0.3

### code
```
function registeredLayoutStore() {
  return {
    state: require('./store/state').default,
    actions: require('./store/actions').default,
    getters: require('./store/getters').default,
    mutations: require('./store/mutations').default
  };
}
```

### Steps to reproduce
- run vite build
- run vite preview

### What is Expected?
no error when use `require`

### What is actually happening?
Uncaught ReferenceError: require is not defined

**Comment by AugustBrenner** [comment]
I am still having this issue on Vite 4.4.3 and vite-plugin-commonjs 1.0.3.

**Comment by MRezaKarimi** [comment]
Same problem with v1.0.3
