### ISSUE TITLE
[vite-plugin-require-context] ViteRequireContext: is not a function

### ISSUE THREAD

**Issue by ayush-dedhia25** [originjs/vite-plugins#45]
### Steps to reproduce
Import it in ```vite.config.js``` then add it in the plugins array.
Let me show you what I mean...
```javascript
import ViteRequireContext from '@originjs/vite-plugin-require-context';
import react from '@vitejs/plugin-react-swc';
import { defineConfig } from 'vite';

// https://vitejs.dev/config/
export default defineConfig({
	plugins: [ViteRequireContext(), react()],
});
```

### What is Expected?
Expected to load all the files within the specified folder using ```require.context()``` method.
for instance my code snippet is as below
```javascript
export const heroTextureImports = importAllImages(
	require.context('../../assets', false, /\.(png|jpe?g|svg)/),
);
```

### What is actually happening?
Throwing TypeError: ```ViteRequireContext``` is not a function.

### Version
@originjs/vite-plugin-require-context: ```"^1.0.9"```
react: ```"^18.2.0"```
node: ```"v18.12.1"```

**Comment by PeterAlfredLee** [comment]
Hi @ayush-dedhia25 
Do you configure `type: "module"` in your `package.json`? If so, could you try to remove it and then have a try?

**Comment by ayush-dedhia25** [comment]
Yeah it fixed that!! Thanks for assisting :)

**Comment by larabr** [comment]
Does this mean the plugin is not compatible with modules?

**Comment by vesper8** [comment]
I'm trying to get rid of this other warning `The CJS build of Vite's Node API is deprecated` and for that I need to add `type:module` to `package.json` and rename `vite.config.js` to `vite.config.mjs` and this is indeed causing the error mentioned here.

Is there a workaround?
