### ISSUE TITLE
运行 vite build 时打包错误

### ISSUE THREAD

**Issue by vxhly** [originjs/vite-plugins#7]
### Versions

- originjs: 
"@originjs/vite-plugin-require-context": "^1.0.6",
- node: 
 14.17.3 
- npm: 
 7.21.0
### Reproduction

<details open>
<summary>Additional Details</summary>
<br>

</details>

### Steps to reproduce

```
require.context('codemirror/addon/fold', true, /^\.\/[\s\S]+\/*\.(js|css)$/)
```

在运行 vite build 的时候报错

![image](https://user-images.githubusercontent.com/17906558/130933298-c5918596-a084-4f1f-9f7b-8b3e49ca7e70.png)
解析出来的正则表达式不是完整的

**Comment by PeterAlfredLee** [comment]
Hi @vxhly 
Thank you for your reporting.
I fixed this and published a new version 1.0.7. Please have a look.
---
嗨 @vxhly
感谢您的报告。
我修复了这个问题并发布了一个新版本 1.0.7。 请看一看。

**Comment by vxhly** [comment]
已解决，谢谢作者
