### ISSUE TITLE
运行失败

### ISSUE THREAD

**Issue by Minori-ty** [originjs/vite-plugins#8]
![image](https://user-images.githubusercontent.com/79521943/132103485-5c0c439f-c6b6-43da-9918-0db5d3ec137a.png)
![image](https://user-images.githubusercontent.com/79521943/132103490-45106630-55fc-4422-815e-2e884f756c37.png)

改成’vite-plugin-commonjs‘则报错
![image](https://user-images.githubusercontent.com/79521943/132103511-d59c212f-b4fe-4d20-a493-1b8f937e817c.png)

node v14.17.5
vue v3.2.6
vite v2.5.2

**Comment by jiawulin001** [comment]
Hi,please provide more details, eg. a reproduction repo will be better, Thx!

是哪个地方改成`vite-plugin-commonjs`报错?能提供一个复现仓库就最好了。

**Comment by Minori-ty** [comment]
> Hi,please provide more details, eg. a reproduction repo will be better, Thx!
> 
> 是哪个地方改成`vite-plugin-commonjs`报错?能提供一个复现仓库就最好了。

我用的是electron+serialport，配置挺繁琐的，挺难复现的。
